name: Build
on: [push, pull_request]
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Bun Version
        run: bun -v
      - name: Day 01
        run: bun test --test-name-pattern day01
      - name: Day 02
        run: bun test --test-name-pattern day02